export const SOCKET_EVENTS = {
  ROOM_CREATE: 'room:create',
  ROOM_JOIN: 'room:join',
  ROOM_LEAVE: 'room:leave',
  ROOM_UPDATE: 'room:update',
  GAME_START: 'game:start',
  GAME_CHOOSE_WORD: 'game:chooseWord',
  GAME_UPDATE: 'game:update',
  GAME_TIMER: 'game:timer',
  GAME_HINT: 'game:hint',
  GAME_DRAWING: 'game:drawing',
  GAME_GUESS: 'game:guess',
  GAME_ROUND_END: 'game:roundEnd',
  GAME_NEXT_ROUND: 'game:nextRound',
  GAME_END: 'game:end',
  GAME_REPLAY: 'game:replay',
  MODERATION_MUTE: 'moderation:mute',
  MODERATION_KICK: 'moderation:kick',
}; 